### PR TITLE
fix(ilanzou): wrong total capacity

### LINKED ISSUE #1420: [BUG] 蓝奏云优享版存储空间显示异常
### 请确认以下事项

- [x] 我已确认阅读并同意 [AGPL-3.0 第15条](https://www.gnu.org/licenses/agpl-3.0.txt#:~:text=15.%20Disclaimer%20of%20Warranty.) 。
本程序不提供任何明示或暗示的担保，使用风险由您自行承担。

- [x] 我已确认阅读并同意 [AGPL-3.0 第16条](https://www.gnu.org/licenses/agpl-3.0.txt#:~:text=16.%20Limitation%20of%20Liability.) 。
无论何种情况，版权持有人或其他分发者均不对使用本程序所造成的任何损失承担责任。

- [x] 我确认我的描述清晰，语法礼貌，能帮助开发者快速定位问题，并符合社区规则。

- [x] 我已确认阅读了[OpenList文档](https://doc.oplist.org)。

- [x] 我已确认没有重复的问题或讨论。

- [x] 我已确认是`OpenList`的问题，而不是其他原因（例如 [网络](https://doc.oplist.org/faq/howto#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host-1) ，`依赖`或`操作`）。

- [x] 我认为此问题必须由`OpenList`处理，而非第三方。

- [x] 我已确认这个问题在最新版本中没有被修复。

### OpenList 版本（必填）

v4.1.4

### 使用的存储驱动（必填）

蓝奏云优享版

### 问题描述（必填）

如图，我的蓝奏云优享版存储显示错误，我一个存储2T空间，另外一个4T空间，均显示有误
Image

### 配置文件内容（必填）

无需，不影响

### 日志（可选）

_No response_

### 复现链接（可选）

无需

### PR DESCRIPTION
**Pull request by KirCute**
## Description / 描述

修复蓝奏云优享版的总空间显示错误，原 issue 剩余空间错误的问题已于 #1407 修复。

## Motivation and Context / 背景

Closes #1420

## How Has This Been Tested? / 测试

未测试

## Checklist / 检查清单

- [x] I have read the [CONTRIBUTING](https://github.com/OpenListTeam/OpenList/blob/main/CONTRIBUTING.md) document.
      我已阅读 [CONTRIBUTING](https://github.com/OpenListTeam/OpenList/blob/main/CONTRIBUTING.md) 文档。
- [x] I have formatted my code with `go fmt` or [prettier](https://prettier.io/).
      我已使用 `go fmt` 或 [prettier](https://prettier.io/) 格式化提交的代码。
- [x] I have added appropriate labels to this PR (or mentioned needed labels in the description if lacking permissions).
      我已为此 PR 添加了适当的标签（如无权限或需要的标签不存在，请在描述中说明，管理员将后续处理）。
- [ ] I have requested review from relevant code authors using the "Request review" feature when applicable.
      我已在适当情况下使用"Request review"功能请求相关代码作者进行审查。
- [ ] I have updated the repository accordingly (If it’s needed).
      我已相应更新了相关仓库（若适用）。
  - [ ] [OpenList-Frontend](https://github.com/OpenListTeam/OpenList-Frontend) #XXXX
  - [ ] [OpenList-Docs](https://github.com/OpenListTeam/OpenList-Docs) #XXXX

### CODE REVIEW

File: drivers/ilanzou/driver.go [hunk 1]
```diff
@@ -409,7 +409,9 @@ func (d *ILanZou) GetDetails(ctx context.Context) (*model.StorageDetails, error)
 	if err != nil {
 		return nil, err
 	}
-	total := utils.Json.Get(res, "map", "totalSize").ToUint64() * 1024
+	totalSize := utils.Json.Get(res, "map", "totalSize").ToUint64() * 1024
+	rewardSize := utils.Json.Get(res, "map", "rewardSize").ToUint64() * 1024
```
Comment (xrgzs) [inline drivers/ilanzou/driver.go:413]: 这里是 accountMap 还是 map？
